### ISSUE TITLE
Implement Nan v2.0.0

### ISSUE THREAD

**Issue by y-a-v-a** [y-a-v-a/node-gd#10]
Got it to work on branch nan2, but would be nice to implement the AsyncWorker for the gd.Image#fileCallback function.

**Comment by ChALkeR** [comment]
Adding to the list: https://github.com/nodejs/node/issues/2798.

**Comment by y-a-v-a** [comment]
With release of v1.0.0 now runs against nodejs 0.10, 0.12 and 4.0.0 !
🍻cheers!

**Comment by y-a-v-a** [comment]
@ChALkeR thanks for adding me to the list, it gave me the pressure I needed to finish and package.
