### ISSUE TITLE
gd.create is not a function

### ISSUE THREAD

**Issue by skeddles** [y-a-v-a/node-gd#103]
I keep getting this error:

gd.create is not a function

I upgraded to 3.0.0 a couple weeks ago

```
var gd = import('node-gd');
var img = await gd.create(requestedScale*colors.length, requestedScale);
```

edit:
```
var gd = import('node-gd');


async function adfgsadfG() {
    console.log('why isnt gd create a function', typeof gd, gd)
    var img = await gd.create(57, 57);
}

adfgsadfG()```

**Comment by y-a-v-a** [comment]
Is your import statement actually correct? I think it should be either `var gd = require('gd');` or `import gd from 'gd'`

**Comment by skeddles** [comment]
require doesn't work because your package is an ES module, import doesn't work because my app is not an es module. so I gotta use import() instead.

anyway, this seems to have solved it:

```
var GD = require('node-gd');

async function adfgsadfG() {
	let gd = (await GD).default;
	var img = await gd.create(57, 57);
}

adfgsadfG();
```
