### ISSUE TITLE
Get raw image data for use in Buffer

### ISSUE THREAD

**Issue by osxi** [y-a-v-a/node-gd#11]
Is there an easy implementation to get the data from an image? Currently, I'm using .saveImage() and then the result from fs.readFileSync to initialize a Buffer to use the image as an email attachment.

I need to access the raw data without the temporarily saving the image, reading it, then deleting it.

**Comment by y-a-v-a** [comment]
The raw binary data of an image is returned if you call img.pngPtr() on an instance of gd#Image. So for example:
```javascript
var gd = require('node-gd');
var img = gd.createTrueColor(100,100);
var buffer = new Buffer(img.pngPtr(), 'binary');
```
And then you can handle the buffer to your liking. I hope this answers your quetion?
An instance of gd#Image has a lot of these xxxPtr() methods that will return binary data of a specific image type (so xxx can be jpeg, png, bmp, etc.).

**Comment by osxi** [comment]
That does help. Thank you!

**Comment by y-a-v-a** [comment]
You're welcome.
Be aware that the API has changed with version 1.0.0 regarding `gd.create` and `gd.createTrueColor`.

If you want to be as asynchronous as possible, you should use something like:
```javascript
var gd = require('node-gd');

gd.create(100, 100, function(error, img) {
  if (error) throw error;

  // then here manipulate and / or save your image
});
```
Or you should change your existing calls to `gd.create` to `gd.createSync`. If you have any more question, feel free!
🍻 Cheers
