### ISSUE TITLE
get node-gd to build on travis against node 4

### ISSUE THREAD

**Issue by y-a-v-a** [y-a-v-a/node-gd#14]
get node-gd to build on travis against node 4
needs some tweaking

**Comment by crudo** [comment]
Hi @y-a-v-a, is there any progress on building node-gd on node 4?

**Comment by y-a-v-a** [comment]
Hi @crudo, node-gd builds very well on node 4.3.1, even nicely on node 5.7.0. This issue #14 concerns the automated test on Travis, which last October was giving errors. So don't be afraid to install node-gd 1.1.0 on node 4 or node 5, according to my tests, it works great.
Until then, cheers! 🍻

**Comment by y-a-v-a** [comment]
Fixed in fd1111a4102bf821e9c6d35a9bc5d4e245d2cdbf
