### ISSUE TITLE
How can I imagecreatefromjpeg()?

### ISSUE THREAD

**Issue by akocmark** [y-a-v-a/node-gd#17]
Hi I came from a PHP background and came across your module. It looks like this is the one I am looking for, but do you know how can I imagecreatefromjpeg($template) using this module?

Thanks in Advance!

**Comment by y-a-v-a** [comment]
Hi,
Thanks for reaching out. I assume `$template` is a filename? Then best you can do is:
```javascript
var gd = require('gd');
var template = 'path/to/your/image.jpg';
gd.openJpeg(template, function(error, image) {
  if (error) throw error;

  image.flipHorizontal();
  var quality = 100;
  image.saveJpeg('newImage.jpg', quality, function(error) {
    if (error) throw error;
  });
});
```
See also: https://github.com/y-a-v-a/node-gd/tree/stable/doc for more examples.
Be aware that currently node-gd does not build on Windows.
Cheers!
Vincent

**Comment by y-a-v-a** [comment]
Answered.
