### ISSUE TITLE
imageCopy not working

### ISSUE THREAD

**Issue by maaljam** [y-a-v-a/node-gd#25]
Behavior: image copy does not work if the two images are different, but it works if image is the same.

I have spend two days to figure out why, but I failed and started to think that this is a bug since it works in some cases only (same image case).

```
var gd = require('node-gd');
var output = 'image-watermark.png';

var watermark = gd.createFromPng('watermark.png');
var input = gd.createFromPng('input.png');

watermark.alphaBlending(1);
watermark.saveAlpha(1);

var final = watermark.copy(input,0,0,0,0,100,100); // This does NOT work
//var final = watermark.copy(watermark,0,0,0,0,100,100); // This does WORK

final.savePng(output, 0, function(error) {
});
```

**Comment by y-a-v-a** [comment]
Hi, thanks for reaching out.
I've tried to reproduce your error but could not get it. I mean, I don't think this is an error.
```javascript
var gd = require('node-gd');
var output = '../output/image-watermark.png';

var watermark = gd.createFromPng('../input/watermark.png');
var input = gd.createFromPng('../input/input.png');

watermark.alphaBlending(1);
watermark.saveAlpha(1);

// copy watermark onto input, i.e. onto the destination
watermark.copy(input, 0, 0, 0, 0, 100, 100);

// save the destination
input.savePng(output, 0, function(error) {
  if (error) throw error;
});
```

You want to copy the watermark _onto_ a destination image, which is `input` in this case, so you explicitly have to save the destination image, which is `input`. `watermark.copy()` returns `watermark`. The reason for that is that you could chain actions, like so:

```javascript
var gd = require('node-gd');
var output = '../output/image-watermark.png';
var output2 = '../output/image-watermark2.png';

var watermark = gd.createFromPng('../input/watermark.png');
var input = gd.createFromPng('../input/input.png');
var input2 = gd.createFromPng('../input/input2.png');

watermark.alphaBlending(1)
.saveAlpha(1)
.copy(input, 0, 0, 0, 0, 100, 100)
.contrast(-900)
.copy(input2, 0, 0, 0, 0, 100, 100)

input.savePng(output, 0, function(error) {
  if (error) throw error;
});

input2.savePng(output2, 0, function(error) {
  if (error) throw error;
});
```

**Comment by y-a-v-a** [comment]
I've added a working version of your example code, including assets, to the examples repository:
https://github.com/y-a-v-a/node-gd-examples

**Comment by maaljam** [comment]
Cannot THANK you enough for your time and quick response. I had a wrong assumption that image#Copy returns an image data of the final product of the copy operation, that is why I was saving it instead.

Maybe it is a good idea to include your code above as an example of image#copy section in the main readMe page to show currect use of image#copy:
https://github.com/y-a-v-a/node-gd/blob/stable/doc/README.md#gdimagecopydest-dx-dy-sx-sy-width-height

Thanks again for your help

**Comment by y-a-v-a** [comment]
Great! It was on my todo-list ;-) I'll try to update the docs asap.
