### ISSUE TITLE
Is it squareToCircle has BUGS? 

### ISSUE THREAD

**Issue by guolianghu** [y-a-v-a/node-gd#31]
```javascript
const gd = require('node-gd');
gd.openPng(IMAGE_DIR + '1467804398519.png', function(err, avatar){
    avatar
        .saveAlpha(1)
        .alphaBlending(1)
        .squareToCircle(100);
        avatar.savePng(IMAGE_DIR + "test.png");
});
```
after do this, test.png is the same as original。
The png size : 256x256,
node-gd ver :  1.3.1
GD ver: 2.1.1

**Comment by y-a-v-a** [comment]
Hi thanks for reaching out!

Apparently you found a bug! This function has not been documented nor been tested since I maintain this package. It was on my list of low-prio-functions to test. I've made a fix and will hope to release it later today.

Thanks again!

**Comment by y-a-v-a** [comment]
I think this function was so much in legacy that it only supported a very old implementation of libgd... As said, I hope to release later today, some other minor changes in the pipe-line.

**Comment by y-a-v-a** [comment]
@guolianghu fixed in new release which is just out! v.1.4.0 see: https://www.npmjs.com/package/node-gd
