### ISSUE TITLE
node-gyp fails because of util.sh check even after dependencies

### ISSUE THREAD

**Issue by dondreytaylor** [y-a-v-a/node-gd#32]
I've noticed that even after installing all of the dependencies-- specifically "gd" on an AWS EC2 running Ubuntu 14.04 using the command ```sudo apt-get install libgd2-dev # libgd```, node-gyp throws the following error when using ***npm install node-gd***

```
Package gdlib was not found in the pkg-config search path. 
Perhaps you should add the directory containing `gdlib.pc'
to the PKG_CONFIG_PATH environment variable
No package 'gdlib' found
```

What I decided to do was to clone the entire node-gd repo and comment out everything util.sh leaving only ``echo true``, then proceed to run ***npm install***. This would ultimately install node-gd without an issue. 

Just thought I would bring it to your attention. I'm not too familiar with the libgd package and I figure maybe the package gets installed differently with later versions and that the check within util.sh may need to be altered.

**Comment by y-a-v-a** [comment]
Hi thanks for reaching out!
I'll take a look into this. It's probably a difference in naming of the library on Ubuntu in comparison to e.g. Mac.

By the way, which node-gd version were you installing?
Thanks in advance.

**Comment by y-a-v-a** [comment]
Hmm can't seem to reproduce on a fresh Ubuntu install version 14.04.5 LTS... Does this output anything for you?
```
$ gdlib-config --features
```
Does that produce anything similar to the following?
```
GD_GIF GD_GIFANIM GD_OPENPOLYGON GD_ZLIB GD_PNG GD_FREETYPE GD_FONTCONFIG GD_JPEG GD_TIFF GD_WEBP
```

**Comment by dondreytaylor** [comment]
You're welcome!

Okay, so I ran the command 

```$ gdlib-config --features```

and here is what I got: 

```GD_JPEG GD_FREETYPE GD_PNG GD_GIF GD_GIFANIM GD_OPENPOLYGON```

**Comment by y-a-v-a** [comment]
OK so it looks like libgd is installed successfully. I think it's a path issue. What's the output of
`$ gdlib-config --all`

I think I need to add the line below to the beginning of `utils.sh` but con only be sure about that when knowing the output of the above. So if you have some time ;-)

`export PKG_CONFIG_PATH=$PKG_CONFIG_PATH:/usr/local/lib/pkgconfig`

Thanks in advance!

**Comment by y-a-v-a** [comment]
I've added a possible solution since I hadn't heard from @dondreytaylor which is part of v1.4.0
