### ISSUE TITLE
Functions produce error when float is passed when argument expects int

### ISSUE THREAD

**Issue by PatrickQuintal** [y-a-v-a/node-gd#33]
I think a better behaviour, instead of just erroring, is to simply perform a cast?

Its quite cumbersome to have to `Math.round()` every time you pass a variable into the functions and breaks away from the whole idea of Javascript being loosely typed.

Let me know what you think. It seems like the change would just slot into 

[https://github.com/y-a-v-a/node-gd/blob/stable/cpp/node_gd.cc#L79](url)

**Comment by y-a-v-a** [comment]
Just out of curiosity, in which situation do you run into this? E.g. which methods?

**Comment by PatrickQuintal** [comment]
Copy, stringFT, stringFTBOX, (I'm pretty sure any function which uses REQ_INT_ARG)

The use case is this;

A Client gives a non-divisible by 2 asset. We must find the centre of the asset to place some text, (So `width/2`) and you lazily use that in your calculations* without rounding before hand. 

I think its fine to accept node-gd to round for you because its either the developer does it themselves or the library does the exact same thing.

I would like more input from other people if there are actually times where you would need to use anything other then `Math.round` when doing image manipulation?

**Comment by y-a-v-a** [comment]
C++ is a strongly typed language, and node-gd is explicitly a binding to libgd. I think, after merely three years, that I tend to disagree with you and that it is a developer's responsibility to deliver the expected values.
