### ISSUE TITLE
img.filledArc() expected 8 arguments, only 7 listed in the docs

### ISSUE THREAD

**Issue by ivanatora** [y-a-v-a/node-gd#34]
So, I can use img.arc() fine, but if I change it to img.filledArc() with the same parameters, it hangs the app. Nothing is returned and code execution stops there. 

If I try to catch the error, I get `[Error: Expected 8 arguments]`. The documentation states only 7 arguments. Looking at http://php.net/manual/en/function.imagefilledarc.php it seems the last argument is the fill style. It will be good to get it into the api docs.

node v4.4.3
node-gd@1.4.0

**Comment by y-a-v-a** [comment]
Hi thanks for reaching out!
On first sight this looks like a bug indeed. I'll take a look into this as soon as possible.

Cheers 🍺
Vincent

**Comment by y-a-v-a** [comment]
A working example:
```javascript
    gd.create(100, 100, function(error, image) {
      var c1 = image.colorAllocate(200, 50, 0); // red
      var c2 = image.colorAllocate(0, 200, 50); // green
      var c3 = image.colorAllocate(0, 50, 200); // blue

      image.filledArc(50, 50, 80, 80, 0, 225, c2, 4);
      image.arc(46, 46, 80, 80, 0, -90, c3);

      image.saveGif('test.gif', function() {
      });
    });
```

The eighth parameter is a bitwise OR of styles, see also https://github.com/libgd/libgd/blob/4143073c889d36caa421b9ae0d7e71ec500585e7/src/gd.h#L1024

I will update the documentation!
Thanks for reporting this.

**Comment by ivanatora** [comment]
Excellent, thank you! :)
