### ISSUE TITLE
Sending image to client results in image that cannot be displayed

### ISSUE THREAD

**Issue by skeddles** [y-a-v-a/node-gd#39]
I'm using express and trying to send the created image to the client (preferably without saving to disk).

```
//create image
var gd = require('node-gd');
var img = gd.createSync(200, 80);
img.colorAllocate(0, 255, 255);
        
var imageData = img.pngPtr();
res.set('Content-Type', 'image/png');
res.send(imageData);
```

When trying to load the page I get "The image cannot be displayed because it contains errors."

**Comment by y-a-v-a** [comment]
See #38: you can use `res.end(data, 'binary')`.

**Comment by skeddles** [comment]
Thank you very much, that worked! Might be worth throwing an example of that into the docs.
