### ISSUE TITLE
Creating a PNG from RGBA array

### ISSUE THREAD

**Issue by Madd0g** [y-a-v-a/node-gd#41]
Hi,

Is it possible to load a buffer of rgba values with one command? Right now I do `gd.createTrueColor` and then `image.setPixel(x, y, gd.trueColorAlpha(r, g, b, a));` for every pixel.

Thanks

**Comment by y-a-v-a** [comment]
Hi @Madd0g, thanks for reaching out! Could you elaborate a bit more on the context? Why would you go over all pixels and give them a color? You can also draw a square the size of the canvas and set a basic transparent background color and draw upon that. Or am I missing the core of your question?
Cheers,
Vincent

**Comment by Madd0g** [comment]
>Why would you go over all pixels and give them a color?

The pixel data I have is actually an image (captured from a screen buffer), not just colored pixels, it's a large array of ARGB values that I add manually one by one to the PNG. I was wondering if it can be done by passing the entire array instead of drawing one pixel at a time.

**Comment by y-a-v-a** [comment]
And this array of ARGB-values, can't you create a node Buffer from it? Maybe like with `Buffer.from(yourArray)` (see [here](https://nodejs.org/api/buffer.html#buffer_class_method_buffer_from_array))
Then you can pass it directly to `gd.createFromPngPtr(data)` and then you'll have an image object which you can easily save.

**Comment by Madd0g** [comment]
I do have the data as an ArrayBuffer, but I had no idea `createFromPngPtr` worked with anything but actual PNG data (I'm new to graphics processing, have no idea what's the difference).

I'll try it soon, thank you

**Comment by y-a-v-a** [comment]
Hi @Madd0g any progress on this issue?

**Comment by Madd0g** [comment]
really sorry, I switched to another library back then and never found time to re-test, I still have the code that uses node-gd and will get around to testing it at some point in the future to compare performance to my current solution.

**Comment by y-a-v-a** [comment]
Long time no hear, therefore closing.
