### ISSUE TITLE
Getting 22 warnings about NewInstance const being deprecated

### ISSUE THREAD

**Issue by scarabdesign** [y-a-v-a/node-gd#44]
Using Node 6.10.0 and Node-gyp 3.3.1

-> node-gd@1.4.0 install /home/sean/dev1_node6/moth/node_modules/node-gd
-> node-gyp rebuild

make: Entering directory '/home/sean/dev1_node6/moth/node_modules/node-gd/build'
  CXX(target) Release/obj.target/node_gd/cpp/addon.o
In file included from ../cpp/node_gd.cc:27:0,
                 from ../cpp/addon.cc:3:
../cpp/createworker.cc: In member function ‘virtual void CreateWorker::HandleOKCallback()’:
../cpp/createworker.cc:34:80: warning: ‘v8::Local<v8::Object> v8::Function::NewInstance(int, v8::Local<v8::Value>*) const’ is deprecated (declared at /home/sean/.node-gyp/6.10.0/include/node/v8.h:3269): Use maybe version [-Wdeprecated-declarations]
       v8::Local<v8::Object> _image = func->GetFunction()->NewInstance(1, &_arg_);
                                                                                ^
In file included from ../cpp/addon.cc:3:0:
../cpp/node_gd.cc: In static member function ‘static Nan::NAN_METHOD_RETURN_TYPE Gd::ImageCreateSync(Nan::NAN_METHOD_ARGS_TYPE)’:
../cpp/node_gd.cc:144:74: warning: ‘v8::Local<v8::Object> v8::Function::NewInstance(int, v8::Local<v8::Value>*) const’ is deprecated (declared at /home/sean/.node-gyp/6.10.0/include/node/v8.h:3269): Use maybe version [-Wdeprecated-declarations]
     Local<Object> instance = func->GetFunction()->NewInstance(argc, &argv);\
                                                                          ^
../cpp/node_gd.cc:311:3: note: in expansion of macro ‘RETURN_IMAGE’
   RETURN_IMAGE(im);
   ^
../cpp/node_gd.cc: In static member function ‘static Nan::NAN_METHOD_RETURN_TYPE Gd::ImageCreateTrueColorSync(Nan::NAN_METHOD_ARGS_TYPE)’:
../cpp/node_gd.cc:144:74: warning: ‘v8::Local<v8::Object> v8::Function::NewInstance(int, v8::Local<v8::Value>*) const’ is deprecated (declared at /home/sean/.node-gyp/6.10.0/include/node/v8.h:3269): Use maybe version [-Wdeprecated-declarations]
     Local<Object> instance = func->GetFunction()->NewInstance(argc, &argv);\
                                                                          ^
../cpp/node_gd.cc:340:3: note: in expansion of macro ‘RETURN_IMAGE’
   RETURN_IMAGE(im);
   ^
../cpp/node_gd.cc: In static member function ‘static Nan::NAN_METHOD_RETURN_TYPE Gd::CreateFromJpeg(Nan::NAN_METHOD_ARGS_TYPE)’:
../cpp/node_gd.cc:144:74: warning: ‘v8::Local<v8::Object> v8::Function::NewInstance(int, v8::Local<v8::Value>*) const’ is deprecated (declared at /home/sean/.node-gyp/6.10.0/include/node/v8.h:3269): Use maybe version [-Wdeprecated-declarations]
     Local<Object> instance = func->GetFunction()->NewInstance(argc, &argv);\
                                                                          ^
../cpp/node_gd.cc:154:5: note: in expansion of macro ‘RETURN_IMAGE’
     RETURN_IMAGE(im)                                                    \
     ^
../cpp/node_gd.cc:343:1: note: in expansion of macro ‘DECLARE_CREATE_FROM’
 DECLARE_CREATE_FROM(Jpeg)
 ^
../cpp/node_gd.cc: In static member function ‘static Nan::NAN_METHOD_RETURN_TYPE Gd::CreateFromJpegPtr(Nan::NAN_METHOD_ARGS_TYPE)’:
../cpp/node_gd.cc:144:74: warning: ‘v8::Local<v8::Object> v8::Function::NewInstance(int, v8::Local<v8::Value>*) const’ is deprecated (declared at /home/sean/.node-gyp/6.10.0/include/node/v8.h:3269): Use maybe version [-Wdeprecated-declarations]
     Local<Object> instance = func->GetFunction()->NewInstance(argc, &argv);\
                                                                          ^
../cpp/node_gd.cc:173:5: note: in expansion of macro ‘RETURN_IMAGE’
     RETURN_IMAGE(im)                                                    \
     ^
../cpp/node_gd.cc:343:1: note: in expansion of macro ‘DECLARE_CREATE_FROM’
 DECLARE_CREATE_FROM(Jpeg)
 ^
../cpp/node_gd.cc: In static member function ‘static Nan::NAN_METHOD_RETURN_TYPE Gd::CreateFromPng(Nan::NAN_METHOD_ARGS_TYPE)’:
../cpp/node_gd.cc:144:74: warning: ‘v8::Local<v8::Object> v8::Function::NewInstance(int, v8::Local<v8::Value>*) const’ is deprecated (declared at /home/sean/.node-gyp/6.10.0/include/node/v8.h:3269): Use maybe version [-Wdeprecated-declarations]
     Local<Object> instance = func->GetFunction()->NewInstance(argc, &argv);\
                                                                          ^
../cpp/node_gd.cc:154:5: note: in expansion of macro ‘RETURN_IMAGE’
     RETURN_IMAGE(im)                                                    \
     ^
../cpp/node_gd.cc:344:1: note: in expansion of macro ‘DECLARE_CREATE_FROM’
 DECLARE_CREATE_FROM(Png)
 ^
../cpp/node_gd.cc: In static member function ‘static Nan::NAN_METHOD_RETURN_TYPE Gd::CreateFromPngPtr(Nan::NAN_METHOD_ARGS_TYPE)’:
../cpp/node_gd.cc:144:74: warning: ‘v8::Local<v8::Object> v8::Function::NewInstance(int, v8::Local<v8::Value>*) const’ is deprecated (declared at /home/sean/.node-gyp/6.10.0/include/node/v8.h:3269): Use maybe version [-Wdeprecated-declarations]
     Local<Object> instance = func->GetFunction()->NewInstance(argc, &argv);\
                                                                          ^
../cpp/node_gd.cc:173:5: note: in expansion of macro ‘RETURN_IMAGE’
     RETURN_IMAGE(im)                                                    \
     ^
../cpp/node_gd.cc:344:1: note: in expansion of macro ‘DECLARE_CREATE_FROM’
 DECLARE_CREATE_FROM(Png)
 ^
../cpp/node_gd.cc: In static member function ‘static Nan::NAN_METHOD_RETURN_TYPE Gd::CreateFromGif(Nan::NAN_METHOD_ARGS_TYPE)’:
../cpp/node_gd.cc:144:74: warning: ‘v8::Local<v8::Object> v8::Function::NewInstance(int, v8::Local<v8::Value>*) const’ is deprecated (declared at /home/sean/.node-gyp/6.10.0/include/node/v8.h:3269): Use maybe version [-Wdeprecated-declarations]
     Local<Object> instance = func->GetFunction()->NewInstance(argc, &argv);\
                                                                          ^
../cpp/node_gd.cc:154:5: note: in expansion of macro ‘RETURN_IMAGE’
     RETURN_IMAGE(im)                                                    \
     ^
../cpp/node_gd.cc:345:1: note: in expansion of macro ‘DECLARE_CREATE_FROM’
 DECLARE_CREATE_FROM(Gif)
 ^
../cpp/node_gd.cc: In static member function ‘static Nan::NAN_METHOD_RETURN_TYPE Gd::CreateFromGifPtr(Nan::NAN_METHOD_ARGS_TYPE)’:
../cpp/node_gd.cc:144:74: warning: ‘v8::Local<v8::Object> v8::Function::NewInstance(int, v8::Local<v8::Value>*) const’ is deprecated (declared at /home/sean/.node-gyp/6.10.0/include/node/v8.h:3269): Use maybe version [-Wdeprecated-declarations]
     Local<Object> instance = func->GetFunction()->NewInstance(argc, &argv);\
                                                                          ^
../cpp/node_gd.cc:173:5: note: in expansion of macro ‘RETURN_IMAGE’
     RETURN_IMAGE(im)                                                    \
     ^
../cpp/node_gd.cc:345:1: note: in expansion of macro ‘DECLARE_CREATE_FROM’
 DECLARE_CREATE_FROM(Gif)
 ^
../cpp/node_gd.cc: In static member function ‘static Nan::NAN_METHOD_RETURN_TYPE Gd::CreateFromGd2(Nan::NAN_METHOD_ARGS_TYPE)’:
../cpp/node_gd.cc:144:74: warning: ‘v8::Local<v8::Object> v8::Function::NewInstance(int, v8::Local<v8::Value>*) const’ is deprecated (declared at /home/sean/.node-gyp/6.10.0/include/node/v8.h:3269): Use maybe version [-Wdeprecated-declarations]
     Local<Object> instance = func->GetFunction()->NewInstance(argc, &argv);\
                                                                          ^
../cpp/node_gd.cc:154:5: note: in expansion of macro ‘RETURN_IMAGE’
     RETURN_IMAGE(im)                                                    \
     ^
../cpp/node_gd.cc:346:1: note: in expansion of macro ‘DECLARE_CREATE_FROM’
 DECLARE_CREATE_FROM(Gd2)
 ^
../cpp/node_gd.cc: In static member function ‘static Nan::NAN_METHOD_RETURN_TYPE Gd::CreateFromGd2Ptr(Nan::NAN_METHOD_ARGS_TYPE)’:
../cpp/node_gd.cc:144:74: warning: ‘v8::Local<v8::Object> v8::Function::NewInstance(int, v8::Local<v8::Value>*) const’ is deprecated (declared at /home/sean/.node-gyp/6.10.0/include/node/v8.h:3269): Use maybe version [-Wdeprecated-declarations]
     Local<Object> instance = func->GetFunction()->NewInstance(argc, &argv);\
                                                                          ^
../cpp/node_gd.cc:173:5: note: in expansion of macro ‘RETURN_IMAGE’
     RETURN_IMAGE(im)                                                    \
     ^
../cpp/node_gd.cc:346:1: note: in expansion of macro ‘DECLARE_CREATE_FROM’
 DECLARE_CREATE_FROM(Gd2)
 ^
../cpp/node_gd.cc: In static member function ‘static Nan::NAN_METHOD_RETURN_TYPE Gd::CreateFromWBMP(Nan::NAN_METHOD_ARGS_TYPE)’:
../cpp/node_gd.cc:144:74: warning: ‘v8::Local<v8::Object> v8::Function::NewInstance(int, v8::Local<v8::Value>*) const’ is deprecated (declared at /home/sean/.node-gyp/6.10.0/include/node/v8.h:3269): Use maybe version [-Wdeprecated-declarations]
     Local<Object> instance = func->GetFunction()->NewInstance(argc, &argv);\
                                                                          ^
../cpp/node_gd.cc:154:5: note: in expansion of macro ‘RETURN_IMAGE’
     RETURN_IMAGE(im)                                                    \
     ^
../cpp/node_gd.cc:347:1: note: in expansion of macro ‘DECLARE_CREATE_FROM’
 DECLARE_CREATE_FROM(WBMP)
 ^
../cpp/node_gd.cc: In static member function ‘static Nan::NAN_METHOD_RETURN_TYPE Gd::CreateFromWBMPPtr(Nan::NAN_METHOD_ARGS_TYPE)’:
../cpp/node_gd.cc:144:74: warning: ‘v8::Local<v8::Object> v8::Function::NewInstance(int, v8::Local<v8::Value>*) const’ is deprecated (declared at /home/sean/.node-gyp/6.10.0/include/node/v8.h:3269): Use maybe version [-Wdeprecated-declarations]
     Local<Object> instance = func->GetFunction()->NewInstance(argc, &argv);\
                                                                          ^
../cpp/node_gd.cc:173:5: note: in expansion of macro ‘RETURN_IMAGE’
     RETURN_IMAGE(im)                                                    \
     ^
../cpp/node_gd.cc:347:1: note: in expansion of macro ‘DECLARE_CREATE_FROM’
 DECLARE_CREATE_FROM(WBMP)
 ^
../cpp/node_gd.cc: In static member function ‘static Nan::NAN_METHOD_RETURN_TYPE Gd::CreateFromBmp(Nan::NAN_METHOD_ARGS_TYPE)’:
../cpp/node_gd.cc:144:74: warning: ‘v8::Local<v8::Object> v8::Function::NewInstance(int, v8::Local<v8::Value>*) const’ is deprecated (declared at /home/sean/.node-gyp/6.10.0/include/node/v8.h:3269): Use maybe version [-Wdeprecated-declarations]
     Local<Object> instance = func->GetFunction()->NewInstance(argc, &argv);\
                                                                          ^
../cpp/node_gd.cc:154:5: note: in expansion of macro ‘RETURN_IMAGE’
     RETURN_IMAGE(im)                                                    \
     ^
../cpp/node_gd.cc:353:1: note: in expansion of macro ‘DECLARE_CREATE_FROM’
 DECLARE_CREATE_FROM(Bmp);
 ^
../cpp/node_gd.cc: In static member function ‘static Nan::NAN_METHOD_RETURN_TYPE Gd::CreateFromBmpPtr(Nan::NAN_METHOD_ARGS_TYPE)’:
../cpp/node_gd.cc:144:74: warning: ‘v8::Local<v8::Object> v8::Function::NewInstance(int, v8::Local<v8::Value>*) const’ is deprecated (declared at /home/sean/.node-gyp/6.10.0/include/node/v8.h:3269): Use maybe version [-Wdeprecated-declarations]
     Local<Object> instance = func->GetFunction()->NewInstance(argc, &argv);\
                                                                          ^
../cpp/node_gd.cc:173:5: note: in expansion of macro ‘RETURN_IMAGE’
     RETURN_IMAGE(im)                                                    \
     ^
../cpp/node_gd.cc:353:1: note: in expansion of macro ‘DECLARE_CREATE_FROM’
 DECLARE_CREATE_FROM(Bmp);
 ^
../cpp/node_gd.cc: In static member function ‘static Nan::NAN_METHOD_RETURN_TYPE Gd::CreateFromGd2Part(Nan::NAN_METHOD_ARGS_TYPE)’:
../cpp/node_gd.cc:144:74: warning: ‘v8::Local<v8::Object> v8::Function::NewInstance(int, v8::Local<v8::Value>*) const’ is deprecated (declared at /home/sean/.node-gyp/6.10.0/include/node/v8.h:3269): Use maybe version [-Wdeprecated-declarations]
     Local<Object> instance = func->GetFunction()->NewInstance(argc, &argv);\
                                                                          ^
../cpp/node_gd.cc:381:3: note: in expansion of macro ‘RETURN_IMAGE’
   RETURN_IMAGE(im);
   ^
../cpp/node_gd.cc: In static member function ‘static Nan::NAN_METHOD_RETURN_TYPE Gd::CreateFromGd2PartPtr(Nan::NAN_METHOD_ARGS_TYPE)’:
../cpp/node_gd.cc:144:74: warning: ‘v8::Local<v8::Object> v8::Function::NewInstance(int, v8::Local<v8::Value>*) const’ is deprecated (declared at /home/sean/.node-gyp/6.10.0/include/node/v8.h:3269): Use maybe version [-Wdeprecated-declarations]
     Local<Object> instance = func->GetFunction()->NewInstance(argc, &argv);\
                                                                          ^
../cpp/node_gd.cc:399:3: note: in expansion of macro ‘RETURN_IMAGE’
   RETURN_IMAGE(im);
   ^
../cpp/node_gd.cc: In static member function ‘static Nan::NAN_METHOD_RETURN_TYPE Gd::Image::Crop(Nan::NAN_METHOD_ARGS_TYPE)’:
../cpp/node_gd.cc:144:74: warning: ‘v8::Local<v8::Object> v8::Function::NewInstance(int, v8::Local<v8::Value>*) const’ is deprecated (declared at /home/sean/.node-gyp/6.10.0/include/node/v8.h:3269): Use maybe version [-Wdeprecated-declarations]
     Local<Object> instance = func->GetFunction()->NewInstance(argc, &argv);\
                                                                          ^
../cpp/node_gd.cc:2002:3: note: in expansion of macro ‘RETURN_IMAGE’
   RETURN_IMAGE(newImage);
   ^
../cpp/node_gd.cc: In static member function ‘static Nan::NAN_METHOD_RETURN_TYPE Gd::Image::CropAuto(Nan::NAN_METHOD_ARGS_TYPE)’:
../cpp/node_gd.cc:144:74: warning: ‘v8::Local<v8::Object> v8::Function::NewInstance(int, v8::Local<v8::Value>*) const’ is deprecated (declared at /home/sean/.node-gyp/6.10.0/include/node/v8.h:3269): Use maybe version [-Wdeprecated-declarations]
     Local<Object> instance = func->GetFunction()->NewInstance(argc, &argv);\
                                                                          ^
../cpp/node_gd.cc:2016:3: note: in expansion of macro ‘RETURN_IMAGE’
   RETURN_IMAGE(newImage);
   ^
../cpp/node_gd.cc: In static member function ‘static Nan::NAN_METHOD_RETURN_TYPE Gd::Image::CropThreshold(Nan::NAN_METHOD_ARGS_TYPE)’:
../cpp/node_gd.cc:144:74: warning: ‘v8::Local<v8::Object> v8::Function::NewInstance(int, v8::Local<v8::Value>*) const’ is deprecated (declared at /home/sean/.node-gyp/6.10.0/include/node/v8.h:3269): Use maybe version [-Wdeprecated-declarations]
     Local<Object> instance = func->GetFunction()->NewInstance(argc, &argv);\
                                                                          ^
../cpp/node_gd.cc:2026:3: note: in expansion of macro ‘RETURN_IMAGE’
   RETURN_IMAGE(newImage);
   ^
../cpp/node_gd.cc: In static member function ‘static Nan::NAN_METHOD_RETURN_TYPE Gd::Image::SquareToCircle(Nan::NAN_METHOD_ARGS_TYPE)’:
../cpp/node_gd.cc:144:74: warning: ‘v8::Local<v8::Object> v8::Function::NewInstance(int, v8::Local<v8::Value>*) const’ is deprecated (declared at /home/sean/.node-gyp/6.10.0/include/node/v8.h:3269): Use maybe version [-Wdeprecated-declarations]
     Local<Object> instance = func->GetFunction()->NewInstance(argc, &argv);\
                                                                          ^
../cpp/node_gd.cc:2168:3: note: in expansion of macro ‘RETURN_IMAGE’
   RETURN_IMAGE(newImage);
   ^
../cpp/node_gd.cc: In static member function ‘static Nan::NAN_METHOD_RETURN_TYPE Gd::Image::CreatePaletteFromTrueColor(Nan::NAN_METHOD_ARGS_TYPE)’:
../cpp/node_gd.cc:144:74: warning: ‘v8::Local<v8::Object> v8::Function::NewInstance(int, v8::Local<v8::Value>*) const’ is deprecated (declared at /home/sean/.node-gyp/6.10.0/include/node/v8.h:3269): Use maybe version [-Wdeprecated-declarations]
     Local<Object> instance = func->GetFunction()->NewInstance(argc, &argv);\
                                                                          ^
../cpp/node_gd.cc:2189:3: note: in expansion of macro ‘RETURN_IMAGE’
   RETURN_IMAGE(newImage);
   ^
  SOLINK_MODULE(target) Release/obj.target/node_gd.node
  COPY Release/node_gd.node
make: Leaving directory '/home/sean/dev1_node6/moth/node_modules/node-gd/build

**Comment by y-a-v-a** [comment]
Hi @scarabdesign thanks for reaching out. I will dig into this soon and report back to you.
Regards, Vincent

**Comment by scarabdesign** [comment]
Great! Seems to build now when pointing to the the mater branch. Will you update the version?

**Comment by y-a-v-a** [comment]
Hi, yes it builds now indeed, since I updated usage of some functions more according to https://github.com/nodejs/nan
Downside indeed is that in some cases it still fails no including node_gd.node

**Comment by y-a-v-a** [comment]
Just published version 1.5.0 to npmjs.org which fixes the above issue.
