### ISSUE TITLE
Just to let you know, npm page points to /doc, not /docs

### ISSUE THREAD

**Issue by CreativeCactus** [y-a-v-a/node-gd#45]
That's all :)

**Comment by y-a-v-a** [comment]
Thanks for reaching out! I haven't published to NPM after I changed that in commit 01b764e0bf5e594caf25588b598327365658e011

I'll publish somewhere soon a new version with correct paths. Thanks!
Regards, Vincent

**Comment by y-a-v-a** [comment]
Just published version 1.5.0 to npm which fixes this issue.
