### ISSUE TITLE
gd.openFile returns no error with null

### ISSUE THREAD

**Issue by XadillaX** [y-a-v-a/node-gd#49]
```js
gd.openFile(filename, function(err, img) {
    // both err and img are null
});
```

But filename actually is a picture filename.

**Comment by y-a-v-a** [comment]
Hi thanks for reaching out. Sorry for the late reply, I was on holidays i.e. not able to respond to any issues. I'll take a look as soon as I have time.

**Comment by y-a-v-a** [comment]
@XadillaX do you have an example image that caused this?

**Comment by y-a-v-a** [comment]
Too long no response so assuming no longer an issue.
