### ISSUE TITLE
Failing to build on GD library 2.1.1 with TIFF disabled

### ISSUE THREAD

**Issue by raabbajam** [y-a-v-a/node-gd#5]
I can not `npm install node-gd`. Here are some infomations:
```
module.js:356
  Module._extensions[extension](this, filename);
                               ^
Error: /opt/lampp/htdocs/expressjs/stebeneva.ru/node_modules/node-gd/build/Release/node_gd.node: undefined symbol: gdImageTiffPtr
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/opt/lampp/htdocs/expressjs/stebeneva.ru/node_modules/node-gd/js/node-gd.js:44:17)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/opt/lampp/htdocs/expressjs/stebeneva.ru/app.js:14:31)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
```

From error log, I assumed this is because I can not build some `tiff` function which is `gdImageTiffPtr`. I have no idea how to enable TIFF features from GD library directly. I use Ubuntu 12.04, and the ones from Ubuntu repository is version 2.0. So I build with following instruction from https://github.com/libgd/libgd/tree/master/docs but I can not figure out how to enable TIFF support.

Here is my GD config
```
❯ gdlib-config --all     
GD library  2.1.1
includedir: /usr/local/include
cflags:     -I/usr/local/include
ldflags:    
libs:       -ljpeg -lz -lm  -lpng12   -lfreetype   -lfontconfig   -lfontconfig -lXpm -lX11   
libdir:     /usr/local/lib
features:   GD_XPM GD_JPEG GD_FONTCONFIG GD_FREETYPE GD_PNG GD_GIF GD_GIFANIM GD_OPENPOLYGON
```

On node-gd readme, it mentioned that this module should still support old GD version, with main differences in function availability. I hope some TIFF function will not break module build.

Thank you. :beer:  :+1:

**Comment by y-a-v-a** [comment]
Hi thanks for the feedback, I really appreciate it, since I am not able to test all installed variants of libgd ;-)
But I do want to support as many different configurations as possible!! So I will try to fix this as soon as possible (takes me  2 or 3 days), so the build will be successful on your system. I will keep you informed in this thread.
Cheers!

**Comment by y-a-v-a** [comment]
Ok so I think I have fixed it right now alread: I have added conditionals around the tiff functions for when libtiff not is available. This should hopefully build successfully on your system. If you have any more questions, please don't hesitate.
Cheers! 🍺

**Comment by raabbajam** [comment]
Hey, @y-a-v-a!

I don't know what causing this, but it looks like several methods that under gdlibs 2.1 doesn't work for me. In the end, I commented all methods that my machine can not find.

So after several times running, error, commenting out the undefined methods on `node-gd.cpp`, rebuild, in the end I comment out everything under `LATEST_GD` conditional check. And then it is working wonderfully.

But just to make sure you have fixed the tiff library problem, I `npm rm node-gd`, `npm cache clean node-gd` and `npm install node-gd`. And yes, the conditional check on libtiff is working. But now it has other error on `BmpPtr`. What do you think causing this?

Here are some information:
```
module.js:356
  Module._extensions[extension](this, filename);
                               ^
Error: /opt/lampp/htdocs/expressjs/stebeneva.ru/node_modules/node-gd/build/Release/node_gd.node: undefined symbol: gdImageBmpPtr
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/opt/lampp/htdocs/expressjs/stebeneva.ru/node_modules/node-gd/js/node-gd.js:44:17)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/opt/lampp/htdocs/expressjs/stebeneva.ru/app.js:14:10)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
```
It says, it can not find `gdImageBmpPtr`.
And this is the gdlib-config
```
GD library  2.1.1
includedir: /usr/local/include
cflags:     -I/usr/local/include
ldflags:    
libs:       -ljpeg -lz -lm  -lpng12   -lfreetype   -lfontconfig   -lfontconfig -lXpm -lX11    -ltiff 
libdir:     /usr/local/lib
features:   GD_TIFF GD_XPM GD_JPEG GD_FONTCONFIG GD_FREETYPE GD_PNG GD_GIF GD_GIFANIM GD_OPENPOLYGON
```

I also try it on my other machine, with GD library 2.0. It also has some errors, can you check it?
```

module.js:356
  Module._extensions[extension](this, filename);
                               ^
Error: /node/apps/stebeneva.ru/node_modules/node-gd/build/Release/node_gd.node: undefined symbol: gdImageEllipse
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/node/apps/stebeneva.ru/node_modules/node-gd/js/node-gd.js:44:17)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/node/apps/stebeneva.ru/app.js:14:10)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
```
It says it cannot find `gdImageEllipse`
```
GD library  2.0.36
includedir: /usr/include
cflags:     -I/usr/include
ldflags:     -L/usr/lib/i386-linux-gnu  -L/usr/lib/i386-linux-gnu -Wl,-Bsymbolic-functions -Wl,-z,relro
libs:       -lXpm -lX11 -ljpeg -lfontconfig -lfreetype -lpng12 -lz -lm  
libdir:     /usr/lib/i386-linux-gnu
features:   GD_XPM GD_JPEG GD_FONTCONFIG GD_FREETYPE GD_PNG GD_GIF GD_GIFANIM GD_OPENPOLYGON
```
Or was it supposed to use older version of node-gd?

Thanks.

**Comment by y-a-v-a** [comment]
Hi @raabbajam,
I added LATEST_GD and I just noticed that the LATEST_GD-check only checks for the first two release numbers (like for the 2 and 1 in 2.1.0) and not taking into account the last number. I will change this as soon as I have time.

Apparently GD_BMP is not present on your first machine. Also, it appears that on your other machine, the check for LATEST_GD is not fully correclty working. I'll fix that too. 

Thanks for the response! 👍

**Comment by y-a-v-a** [comment]
Hi,
Just to inform you: I'm rewriting parts of the c++ code to better distinguish between versions of libgd, but it takes me some more days before it will be done and tested.
Cheers 🍻

**Comment by raabbajam** [comment]
Yes, I think that will be the best. May I suggest to also expand to feature checking with combination to version checking (instead of LATEST or not), because some older version with and without some features enabled will have different function.

Cheers back to you :+1:

**Comment by y-a-v-a** [comment]
Yes that's exatcly what I wanted to implement: version based feature detection. But it takes some time to test this, since I'd like to test it against real-world libgd versions and configurations. I'll probably set up a virtual machine and test it in there.
Thanks for the tip.

**Comment by afanasy** [comment]
+1
`npm install node-gd` doesn't work
I'm using Ubuntu Trusty 14.04 LTS + node v0.12 + GD library  2.1.1-dev@ (from apt-get install libgd2-xpm-dev)

**Comment by y-a-v-a** [comment]
Thanks for noticing, I worked on it yesterday, hope to publish to NPM today or tomorrow. I'll keep you informed.

**Comment by y-a-v-a** [comment]
@afanasy are you able to paste the console output of npm install? Would help me in fixing this.
Thanks in advance!

**Comment by afanasy** [comment]
npm install node-gd
```
\
> node-gd@0.4.4 install /home/ubuntu/test/node_modules/node-gd
> node-gyp rebuild

make: Entering directory `/home/ubuntu/test/node_modules/node-gd/build'
  CXX(target) Release/obj.target/node_gd/cpp/node-gd.o
../cpp/node-gd.cpp: In static member function ‘static void Gd::CreateFromFile(const v8::FunctionCallbackInfo<v8::Value>&)’:
../cpp/node-gd.cpp:218:48: error: ‘gdImageCreateFromFile’ was not declared in this scope
     gdImagePtr im = gdImageCreateFromFile(*path);
                                                ^
../cpp/node-gd.cpp: In static member function ‘static void Gd::Image::File(const v8::FunctionCallbackInfo<v8::Value>&)’:
../cpp/node-gd.cpp:681:29: error: ‘gdImageFile’ was not declared in this scope
       gdImageFile(*im, *path);
                             ^
../cpp/node-gd.cpp: In static member function ‘static void Gd::Image::FileCallback(const v8::FunctionCallbackInfo<v8::Value>&)’:
../cpp/node-gd.cpp:695:43: error: ‘gdImageFile’ was not declared in this scope
       bool result = gdImageFile(*im, *path);
                                           ^
make: *** [Release/obj.target/node_gd/cpp/node-gd.o] Error 1
make: Leaving directory `/home/ubuntu/test/node_modules/node-gd/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:269:23)
gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1074:12)
gyp ERR! System Linux 3.13.0-24-generic
gyp ERR! command "node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/ubuntu/test/node_modules/node-gd
gyp ERR! node -v v0.12.4
gyp ERR! node-gyp -v v1.0.3
gyp ERR! not ok 
npm ERR! Linux 3.13.0-24-generic
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "node-gd"
npm ERR! node v0.12.4
npm ERR! npm  v2.10.1
npm ERR! code ELIFECYCLE

npm ERR! node-gd@0.4.4 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the node-gd@0.4.4 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the node-gd package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls node-gd
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/ubuntu/test/npm-debug.log
```

**Comment by y-a-v-a** [comment]
So I noticed that on Debian and Ubuntu, libgd2 actually lies abouts its version, since there seems to be a bug in the header file located in `/usr/include/gd.h`.
```c++
#define GD_MAJOR_VERSION 2
#define GD_MINOR_VERSION 1
#define GD_RELEASE_VERSION 0
#define GD_EXTRA_VERSION "dev"
#define GD_VERSION_STRING "2.1.1-dev"
```
Some conditions I've created in node-gd did not work properly because it relied on GD_VERSION_STRING. Now I've decided to rely on a combination of the above.

**Comment by afanasy** [comment]
Wow, interesting.

**Comment by y-a-v-a** [comment]
So I've published a new minor version update `0.5.0`, which distinguishes better between different possible libgd2 versions. Please give it a try and in case of bugs, you're really helping me out with reporting them  😀
See also: https://www.npmjs.com/package/node-gd

Cheers!
🍹

**Comment by y-a-v-a** [comment]
The above should be fixed with 860db8971d58aba56e88463ea0df05dd4c18b3b8

**Comment by afanasy** [comment]
Yes, it builds on my setup now! Thanks!

**Comment by y-a-v-a** [comment]
Good to hear! I've filed a bug report at Debian, hopefullt they're going to fix it.

**Comment by y-a-v-a** [comment]
Just for your information: some methods might not be available on your system. I do not register a complete list in the readme, but you can easily check yourself.
```javascript
// load gd
var gd = require('node-gd');
// list object contents
console.log(gd);
// create an instance of gd#Image
var img = gd.createTrueColor(100,100);
// list the object's properties
console.log(img);
// list the prototype's properties
// if you want to use img.emboss() but it's
// not in these properties, it is not available
// in your libgd2 version either.
console.log(img.__proto__);
// show the GD version.
console.log(gd.getGDVersion());
```
