### ISSUE TITLE
squareToCircle not working

### ISSUE THREAD

**Issue by Mifayo** [y-a-v-a/node-gd#51]
i want to crop an image to circle 
i create transparent image i squareToCircle my image and i copy it to the one i created but it's not working

**Comment by y-a-v-a** [comment]
Hi @Mifayo thanks for reaching out. As far as I can see, squareToCirlce just woks. It's a synchronous function which returns a new image, so you'll have to do something with the resulting image. Be aware that you should supply a radius. If radius is 100 for example, the resulting image will be 200x200 px in size. The below snippet works afaics.
```javascript
var gd = require('node-gd');

gd.openFile('./test.jpg', function(err, trueColor) {
  var newImage = trueColor.squareToCircle(100);

  newImage.saveFile('./square.jpg', function(err) {
  });
});
```

Cheers! 🍻

**Comment by Mifayo** [comment]
hello @y-a-v-a thanks for answering me 
i tried the code u gave me but it gaves me an error
---------------
TypeError: Cannot read property 'saveFile' of null

**Comment by Mifayo** [comment]
it works but don't crop circle it ruin the image

**Comment by y-a-v-a** [comment]
Indeed it doesn't crop the image, it wraps a square image into a circle. The function isn't called: cropSquareToCircle. node-gd is a wrapper around libgd2. There it says: `Apply polar coordinate transformation to an image.` See [here](https://github.com/libgd/libgd/blob/40bec0f38f50e8510f5bb71a82f516d46facde03/src/gdfx.c#L292). As far as I know, there's no circular crop functionality in libg2. You might try it by drawing a transparent circle on a back background, overlay it on you original image and afterwards change the black color to transparent.
Cheers Vincent
