### ISSUE TITLE
How to center align text using node-gd

### ISSUE THREAD

**Issue by haegul** [y-a-v-a/node-gd#53]
Hello. I use node-gd for development some image processing project. I have a question for dev. 

I want to composite multiple texts on some image. And Also the text is aligned center. but ```gd.Image#stringFT(color, font, size, angle, x, y, string, boundingbox)``` doesn't support text align. 
I want multiline text align like [gd-text](https://github.com/stil/gd-text) ```setTextAlign('center', 'center');``` method.

Would you tell me some good idea?
Thanks.

**Comment by y-a-v-a** [comment]
Hi, thanks for reaching out. I will try to find some time to see if it's worth implementing something like that. But just to let you know: in the code behind the php-gd link you supplied you can see the solution they implemented. Basically they just do some maths on the bounding box. This is something you potentially could do in your JS too, of course.
https://github.com/stil/gd-text/blob/b395fef9009bd37e6df137afacf0d25237c1bd61/src/Box.php#L267

Cheers! Vincent

**Comment by haegul** [comment]
Thank you for answer. I will try it! After, I hope node-gd support high API functions like gd-text. (I want to be treated as a subproject later on.)

Cheers!

**Comment by y-a-v-a** [comment]
Hi, well I guess I won't support more than libgd2 itself supports. If you would want to have more higher level functions, please checkout easy-gd for example.
