### ISSUE TITLE
node-gd equivalent of PHP imagecolorsforindex

### ISSUE THREAD

**Issue by marcus-sa** [y-a-v-a/node-gd#57]
I'm enjoying this library so far and have found it very useful to my project.
But I'm at a stage where this library is lacking the only function I need to finish it up.

I have a set of images that are white and some that are statically colored which are not supposed to be recolored. The sets contain from 1-5 images, and some of them can be color-able by the user.
Currently when I try to recolor an image by it's width and height I get something like this:
https://i.imgur.com/s4C60BX.png

But in the PHP equivalent when using imagecolorsforindex and imagecolorat and setting the pixel this doesn't happen.
```
$width = imagesx($image);
	$height = imagesy($image);

	for($x = 0; $x < $width; $x++)
	{
		for($y = 0; $y < $height; $y++)
		{
			$rgb = imagecolorsforindex($image, imagecolorat($image, $x, $y));
			$r = $rgb['red'];
			$g = $rgb['green'];
			$b = $rgb['blue'];
			$a = $rgb['alpha'];

			$r = (($red / 255) * $r);
			$g = (($green / 255) * $g);
			$b = (($blue / 255) * $b);

			imagesetpixel($image, $x, $y, imagecolorallocatealpha($image, $r, $g, $b, $a));
		}
	}
```

At the moment all I've figured out how to do is this:
```
for (let x = 0; x < image.width; x++) {
			for (let y = 0; y < image.height; y++) {
				// @TODO: Find equivalent node-gd fn of PHP imagecolorsforindex

				image.setPixel(x, y, image.colorAllocate(r, g, b))
			}
		}
```

This is probably a feature request, but I'll post it here for now.

**Comment by y-a-v-a** [comment]
Hi thanks for reaching out, sorry for the late reaction. I was looking around in the libgd codebase and found some methods which I did not expose in this module. See: https://github.com/libgd/libgd/blob/master/src/gd.h#L167

If I have time the upcoming weeks, I might be able to expose them to JS. The other option could be that you use the logic from libgd and implement those functions in your own code?
I'll keep you posted.
Regards, Vincent

**Comment by marcus-sa** [comment]
Sadly I wasn't able to implement them myself :disappointed: 
By any chance you'll add the feature when you have time? :smile:

**Comment by y-a-v-a** [comment]
Hi, I meant you might be able to solve it temporarily in JS, something like:
```javascript
const color = 12197020; // css color #ba1c9c, rgb(186, 28, 156), retrieved from e.g. imagecolorat

const red =  (color & 0xFF0000) >> 16; // 186
const green = (color & 0x00FF00) >> 8 // 28
const blue = (color & 0x0000FF) // 156

image.colorAllocate(red, green, blue);
```

**Comment by y-a-v-a** [comment]
That being said, I will see what I can do next weeks.

**Comment by sizkein** [comment]
```
img.getTrueColorPixel(0, 0)
RangeError: Value for "x offset" must be greater than 0
RangeError: Value for "y offset" must be greater than 0
```
getTrueColorPixel does not load the x, y coordinates 0.

**Comment by sizkein** [comment]
```
img.getTrueColorPixel(0, 0)
RangeError: Value for "x offset" must be greater than 0
RangeError: Value for "y offset" must be greater than 0
```
I think it should be bigger than -1.

**Comment by marcus-sa** [comment]
I still don't get how I am supposed to add and get the alpha channel.

**Comment by y-a-v-a** [comment]
Hi @marcus-sa , sorry for the late reply. Getting the alpha value of a color can easily be done with the `alpha` function.

```javascript
var gd = requide('node-gd');
var image = gd.openFile('./input.png');

for (let i = 0; i < image.width; i += 10) {
  var color = image.getTrueColorPixel(i, i);
  console.log(image.alpha(color));
}
```

**Comment by y-a-v-a** [comment]
Side note:
`imagecolorat` is a PHP-specific function which landed for some reason in node-gd, but in node-gd, the same result can be obtained by using either `image.getTrueColorPixel` or `image.getPixel`.

In PHP, `imagecolorsforindex` returns an array of rgba values for a color "index". In node-gd you'd do something like:
```javascript
var gd = requide('node-gd');
var image = gd.openFile('./input.png');

// get the color "index" (as what they call it in PHP)
// on coordinate (10, 10)
var color = image.getTrueColorPixel(10, 10);

// list the individual values per channel
console.log(image.red(color), image.green(color), image.blue(color), image.alpha(color));
```

There is no function in node-gd that returns an array with the color values per channel, like `imagecolorsforindex` in PHP. You will have to create it yourself, maybe likewise:

```javascript
function getColorsForIndex(image, color) {
  return [image.red(color), image.green(color), image.blue(color), image.alpha(color)];
}
```

This might yield to something like `[ 255, 255, 255, 127 ]` for a specific color in an image. Hope that this helps you out.
Regards, Vincent

**Comment by y-a-v-a** [comment]
Too long no reaction, closing
