### ISSUE TITLE
getTrueColorPixel(0, 0) Can not load coordinates

### ISSUE THREAD

**Issue by sizkein** [y-a-v-a/node-gd#59]
```
img.getTrueColorPixel(0, 0)
img.getTrueColorPixel(5, 0)
img.getTrueColorPixel(0, 5)
RangeError: Value for "x offset" must be greater than 0
RangeError: Value for "y offset" must be greater than 0
```
I think it should be bigger than -1.

**Comment by y-a-v-a** [comment]
Hi @sizkein  thanks for reaching out, and good finding. I overlooked it, sorry! A patch will be out later today, probably as version 1.5.3
Cheers! 🍻 Vincent

**Comment by y-a-v-a** [comment]
Release 1.5.3 is out! It should fix this issue.
