### ISSUE TITLE
support open Src ？

### ISSUE THREAD

**Issue by JiaLe1** [y-a-v-a/node-gd#63]
Hi, I'm trying to open image from Src, what the best way to do that?

Thanks

**Comment by y-a-v-a** [comment]
Hi, @JiaLe1, what do you mean with 'from Src'?

**Comment by JiaLe1** [comment]
Yeah, I write this code expect open someone image.
like this:

var gd = require('node-gd');
gd.openFile('https://images/xx.png', function(err, img) {
  if (err) {
    throw err;
  }
}

**Comment by y-a-v-a** [comment]
Hi, @JiaLe1 
You will first need to retrieve it via the standard http(s)-API of node, then store the image data in a Buffer and pass that to node-gd to do something with it. You could use `http.get`, as described here: https://nodejs.org/docs/latest-argon/api/http.html#http_http_get_options_callback and use a buffer to store the response asynchronously, then when http fires 'end' event, then pass the Buffer to node-gd to modify / change the image.
Cheers
Vincent

**Comment by JiaLe1** [comment]
You are a great guys. Thanks for you.

Cheers

**Comment by y-a-v-a** [comment]
thanks!
