### ISSUE TITLE
CreateFromGif dont working!

### ISSUE THREAD

**Issue by manuaranda** [y-a-v-a/node-gd#65]
Hi, 

im using "gd.createFromGif()" and similars functions, but my image.gif, its static and dont move. How can I create an animated gif, from a opened gif? 

Thx!!!!

**Comment by y-a-v-a** [comment]
Hi, thanks for reaching out.
As I understand from your remark, and correct me if I'm wrong, you're trying to open an animated GIF and modify it? As per this issue in the libgd repo (of which node-gd is a NodeJS wrapper / binding), that is not possible: https://github.com/libgd/libgd/issues/396. Currently I have no idea how to get multiple frames from an animated GIF.
Regards,
Vincent

**Comment by y-a-v-a** [comment]
Assuming answered. Closing ticket.
