### ISSUE TITLE
Running on AWS Lambda

### ISSUE THREAD

**Issue by nikoskip** [y-a-v-a/node-gd#66]
Hi,

I'm trying to run `node-gd` on Lambda but I'm getting this error:

> 2018-07-12 17:30:43.268 (-04:00)        d428deda-861a-11e8-9036-57cbb0f6f30c    /var/task/node_modules/node-gd/build/Release/node_gd.node: invalid ELF header
> 2018-07-12 17:30:43.269 (-04:00)        d428deda-861a-11e8-9036-57cbb0f6f30c    Cannot find module '/var/task/node_modules/node-gd/js/../build/default/node_gd.node'
> 2018-07-12 17:30:43.269 (-04:00)        d428deda-861a-11e8-9036-57cbb0f6f30c    Unable to find addon node_gd.node in build directory.

On my local I had to install `gd` and `pkg-config` using brew and it works as expected.

I found the same issue with `node-canvas` but they are supporting Lambda. It needs more steps, but nothing complicated: https://github.com/Automattic/node-canvas/wiki/Installation%3A-AWS-Lambda

It's possible to the same with `node-gd`?

Thanks

**Comment by nikoskip** [comment]
I answer myself: yes, it's possible! 👍 

I went through the [node-canvas guide](https://github.com/Automattic/node-canvas/wiki/Installation%3A-AWS-Lambda) and the only difference is in this case is I needed to copy `libgd.so.2` and `libXpm.so.4` to my `./lib` directory.

Hope this helps someone :)

**Comment by surendiranganesan** [comment]
Hi Nikoskip,

I am facing library issue while executing code.
can you please provide which files needs to be copied. 

regards,
Suren
