### ISSUE TITLE
cropAuto(1) does nothing

### ISSUE THREAD

**Issue by skeddles** [y-a-v-a/node-gd#67]
This should crop an image by the transparency according to the docs. No matter what I do, it always comes out the exact same. I tried it with a generated mockup from a web service as well as a test PNG I made in photoshop, but both have the same result.

```
var gd = require('node-gd');

const PATH = 'test.png';

var mockupImage = gd.createFromPng(PATH);
mockupImage.saveAlpha(1);
mockupImage.cropAuto(1);

mockupImage.savePng('test-output.png', function(err) {
    if(err) console.log('error saving thumbnail: '+err);
    else console.log('thumbnail saved');
});
```
test images:
![test](https://user-images.githubusercontent.com/2721332/48985320-3227c400-f0d4-11e8-86f5-31134904a145.png)
![test 3](https://user-images.githubusercontent.com/2721332/48985322-3522b480-f0d4-11e8-8236-eaee74915173.png)

**Comment by y-a-v-a** [comment]
Hi thanks for reaching out. As I'm maintaining this in my free time, I have to see when I can take a look into this, but I will. Hang on ;-) Cheers, Vincent

**Comment by y-a-v-a** [comment]
Hi, following up on this: as I recall, the issue with cropping a transparent png is an issue with libgd, see:
https://github.com/libgd/libgd/issues/432 and #60. I do not exactly know whether libgd has shipped this fix. An alternative could be to first draw a white background on an new canvas, draw the transparent png on top of it, then crop it and save it. The result will be having a bit of white space...

```javascript
var gd = require('./js/node-gd');

const PATH = './test/48985322-3522b480-f0d4-11e8-8236-eaee74915173.png';

var mockupImage = gd.createFromPng(PATH);
mockupImage.saveAlpha(1);

var bufferImage = gd.createTrueColorSync(mockupImage.width, mockupImage.height);
bufferImage.filledRectangle(0,0,mockupImage.width, mockupImage.height, gd.trueColor(255,255,255));

mockupImage.copy(bufferImage, 0,0,0,0,mockupImage.width, mockupImage.height,mockupImage.width, mockupImage.height);

var newImage = bufferImage.cropAuto(3);

newImage.savePng('./test-output.png', function(err) {
    if(err) console.log('error saving thumbnail: '+err);
    else console.log('thumbnail saved');
});

```

**Comment by y-a-v-a** [comment]
Assuming answered, so closing.
