### ISSUE TITLE
undefined symbol: gdImageCreateFromPngPtr

### ISSUE THREAD

**Issue by alanfernando93** [y-a-v-a/node-gd#68]
Hi.
when wanting to draw in png format I get the following error
undefined symbol: gdImageCreateFromPngPtr

> node /home/criptoanalisis/dev/backend/server/server.js: symbol lookup error: /home/criptoanalisis/dev/backend/node_modules/node-gd/build/Release/node_gd.node: undefined symbol: gdImageCreateFromPngPtr

I've searched everywhere but I can not solve

**Comment by y-a-v-a** [comment]
Probably your build of libgd2 is missing PNG support, either try reinstalling libgd2 or explicitly install its PNG dependency first.
