### ISSUE TITLE
node-gd crashes

### ISSUE THREAD

**Issue by marckris** [y-a-v-a/node-gd#73]
ubuntu 18.04.3 LTS
node v10.16.3
npm 6.9.0
node-gd 1.6.0

When installing using NPM there are many warnings as per attached text file. Nevertheless NPM installs it anyway.

Either when performing Gd.createSync or Gd.createFromJpeg (not sure) but I get a segmentaion fault.
[node-gd-segfault.txt](https://github.com/y-a-v-a/node-gd/files/3537927/node-gd-segfault.txt)

**Comment by marckris** [comment]
More information using gdb backtrace

(gdb) bt
#0  _IO_new_fclose (fp=0x0) at iofclose.c:48
#1  0x00007fffdf7aefa1 in Gd::CreateFromJpeg(Nan::FunctionCallbackInfo<v8::Value> const&) ()
   from /xxx/node_modules/node-gd/build/Release/node_gd.node
#2  0x00007fffdf7a3acf in Nan::imp::FunctionCallbackWrapper(v8::FunctionCallbackInfo<v8::Value> const&) ()
   from /xxx/node_modules/node-gd/build/Release/node_gd.node
#3  0x0000000000b8e6af in v8::internal::MaybeHandle<v8::internal::Object> v8::internal::(anonymous namespace)::HandleApiCallHelper<false>(v8::internal::Isolate*, v8::internal::Handle<v8::internal::HeapObject>, v8::internal::Handle<v8::internal::HeapObject>, v8::internal::Handle<v8::internal::FunctionTemplateInfo>, v8::internal::Handle<v8::internal::Object>, v8::internal::BuiltinArguments) ()

**Comment by y-a-v-a** [comment]
Hi I was off for vacation but back. I will take a look somewhere this week. Regards, Vincent
