### ISSUE TITLE
node-gd fails to install

### ISSUE THREAD

**Issue by flyingspoon** [y-a-v-a/node-gd#77]
`root@root ~/testing # npm install node-gd
npm ERR! Linux 4.15.0-101-generic
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "install" "node-gd"
npm ERR! node v8.10.0
npm ERR! npm  v3.5.2
npm ERR! code EMISSINGARG

npm ERR! typeerror Error: Missing required argument #1
npm ERR! typeerror     at andLogAndFinish (/usr/share/npm/lib/fetch-package-metadata.js:31:3)
npm ERR! typeerror     at fetchPackageMetadata (/usr/share/npm/lib/fetch-package-metadata.js:51:22)
npm ERR! typeerror     at resolveWithNewModule (/usr/share/npm/lib/install/deps.js:456:12)
npm ERR! typeerror     at /usr/share/npm/lib/install/deps.js:190:5
npm ERR! typeerror     at /usr/share/npm/node_modules/slide/lib/async-map.js:52:35
npm ERR! typeerror     at Array.forEach (<anonymous>)
npm ERR! typeerror     at /usr/share/npm/node_modules/slide/lib/async-map.js:52:11
npm ERR! typeerror     at Array.forEach (<anonymous>)
npm ERR! typeerror     at asyncMap (/usr/share/npm/node_modules/slide/lib/async-map.js:51:8)
npm ERR! typeerror     at exports.loadRequestedDeps (/usr/share/npm/lib/install/deps.js:188:3)
npm ERR! typeerror This is an error with npm itself. Please report this error at:
npm ERR! typeerror     <http://github.com/npm/npm/issues>
`

**Comment by y-a-v-a** [comment]
Hi, your NPM version is quite behind, as it is currently in its 6.x version branch. You can update it by running `npm install -g npm`. That _could_ be the issue, but there could be other issues too: did you install all dependencies as described in the readme.md of this project?
Regards,
Vincent

**Comment by y-a-v-a** [comment]
@flyingspoon if you still encounter issues, please drop a note here, or else I will close this issue due to too long inactivity. Regards, Vincent
