### ISSUE TITLE
CentOS node-gyp rebuild Error

### ISSUE THREAD

**Issue by batuhanoztrk** [y-a-v-a/node-gd#78]
Operating System: CentOS 7
Node Version: v14.4.0
Npm Version: 6.14.5
node-gyp: Latest
GCC:  4.8.5

![Ekran Resmi 2020-06-26 11 35 09](https://user-images.githubusercontent.com/34206290/85837733-1cdbb580-b7a1-11ea-80fd-07ac8f3b57e6.png)

**Comment by y-a-v-a** [comment]
Hi @batuhanoztrk , thanks for reaching out. Could you translate the error message shown in your console screen shot? What version of libgd did you install?
Regards, Vincent

**Comment by batuhanoztrk** [comment]
For Centos, I know that libgd consists of gd and gd-devel. Sorry for not paying attention to the language of the screenshot. I forward the log file as an attachment. Thanks for your quick return

gd and gd-devel version: 2.0.35-26.el7

`make: `/root/node_server/project2/node_modules/node-gd/build' entering directory
  CC(target) Release/obj.target/nothing/../node-addon-api/nothing.o
  AR(target) Release/obj.target/../node-addon-api/nothing.a
  COPY Release/nothing.a
  CXX(target) Release/obj.target/node_gd/src/addon.o
In file included from ../src/node_gd.cc:23:0,
                 from ../src/addon.cc:20:
../src/node_gd_workers.cc: In member function 'virtual void CreateFromWebpWorker::Execute()':
../src/node_gd_workers.cc:285:39: hata: 'gdImageCreateFromWebp' not reported in this domain(orbit)
       image = gdImageCreateFromWebp(in);
                                       ^
../src/node_gd_workers.cc: In member function 'virtual void CreateFromBmpWorker::Execute()':
../src/node_gd_workers.cc:316:38: hata: 'gdImageCreateFromBmp' bu etki alanında bildirilmemiş
       image = gdImageCreateFromBmp(in);
                                      ^
../src/node_gd_workers.cc: In member function 'virtual void CreateFromTiffWorker::Execute()':
../src/node_gd_workers.cc:347:39: hata: 'gdImageCreateFromTiff' not reported in this domain(orbit)
       image = gdImageCreateFromTiff(in);
                                       ^
../src/node_gd_workers.cc: In member function 'virtual void FileWorker::Execute()':
../src/node_gd_workers.cc:377:53: hata: 'gdImageFile' not reported in this domain(orbit)
       _success = gdImageFile(*_gdImage, path.c_str());
                                                     ^
../src/node_gd_workers.cc: In member function 'virtual void CreateFromFileWorker::Execute()':
../src/node_gd_workers.cc:429:49: hata: 'gdImageCreateFromFile' not reported in this domain(orbit)
       image = gdImageCreateFromFile(path.c_str());
                                                 ^
../src/node_gd_workers.cc: In member function 'virtual void SaveWebpWorker::Execute()':
../src/node_gd_workers.cc:683:42: hata: 'gdImageWebpEx' bu etki alanında bildirilmemiş
       gdImageWebpEx(*_gdImage, out, level);
                                          ^
../src/node_gd_workers.cc: In member function 'virtual void SaveBmpWorker::Execute()':
../src/node_gd_workers.cc:784:45: hata: 'gdImageBmp' bu etki alanında bildirilmemiş
       gdImageBmp(*_gdImage, out, compression);
                                             ^
../src/node_gd_workers.cc: In member function 'virtual void SaveTiffWorker::Execute()':
../src/node_gd_workers.cc:816:33: hata: 'gdImageTiff' not reported in this domain(orbit)
       gdImageTiff(*_gdImage, out);
                                 ^
make: *** [Release/obj.target/node_gd/src/addon.o] Hata 1
make: `/root/node_server/project2/node_modules/node-gd/build' exiting the directory
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:315:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:276:12)
gyp ERR! System Linux 3.10.0-1127.10.1.el7.x86_64
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /root/node_server/project2/node_modules/node-gd
gyp ERR! node -v v14.4.0
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok 
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! node-gd@2.1.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the node-gd@2.1.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2020-06-26T09_23_54_078Z-debug.log`

[2020-06-26T09_23_54_078Z-debug.log](https://github.com/y-a-v-a/node-gd/files/4836108/2020-06-26T09_23_54_078Z-debug.log)

**Comment by y-a-v-a** [comment]
Hi @batuhanoztrk , thing is, gd version 2.0.35xx is from 2007, which is released 13 years ago... My current guess is that TIFF was not yet supported back then, neither was Webp. I have been trying to keep support via backwards compatibility, but I think your build fails due to either back logic from my side, or the implicit drop of support for that old version. I would suggest to see if you can obtain a more recent version of libgd, either from a CentOS package manager, or via https://github.com/libgd/libgd/releases or via some other package managing tool.
Regards,
Vincent

**Comment by y-a-v-a** [comment]
If I quickly search for gd in CentOS 7 package sources, I see that gd is added in 2014. Looking at CentOS 8, the gd library is of version 2.2.5, of which I know it should work. Reference: http://mirror.centos.org/centos/8/AppStream/x86_64/os/Packages/ just FYI.

**Comment by batuhanoztrk** [comment]
Thank you very much for your support. I updated my server to CentOS 8 and there was no problem.

**Comment by y-a-v-a** [comment]
Thanks for letting me know. Good luck!
