### ISSUE TITLE
Name with_tiff is not defined

### ISSUE THREAD

**Issue by Lnx38** [y-a-v-a/node-gd#9]
![screenshot](https://cloud.githubusercontent.com/assets/13579525/8997628/45d7cc9c-3756-11e5-9092-52cc2afec054.png)

Error after npm install. Windows 10. Python 2.7.10.

Log file: http://www37.zippyshare.com/v/UfIq7Cg9/file.html

**Comment by y-a-v-a** [comment]
Hi thanks for calling out, sorry for the late response.
I'm calling a shell script in binding.gyp that is OS-specific. You could try to use cygwin, but I have no idea weather that would work.
I'm planning to get node-gd to work on Windows, but I have no Windows OS at my disposal and I'm working now on moving node-gd to use Nan v2.0 https://github.com/nodejs/nan which is quite a challenge for me ;-)
🍻cheers!

**Comment by y-a-v-a** [comment]
No plans to get it built on Windows any time soon. Closing.
